/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_docenteestudiantes;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class InicioDocente extends javax.swing.JFrame {

    String nombre1;

    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }

    public String getNombre1() {
        return nombre1;
    }

    AgregarEstudiante agregarEstudiante;

    EliminarEstudiante eliminarEstudiante;

    Docente doc = new Docente();
    Adicionar adi = new Adicionar();
    ModificarNotas modi = new ModificarNotas();
    EliminarNotas eliminarNotas = new EliminarNotas();
    BucarNotas buscarNotas = new BucarNotas();
    ListarNotas lis = new ListarNotas();
    RegistroListadoAsistencia lisAsis = new RegistroListadoAsistencia();
    ListadoAsistencia asis = new ListadoAsistencia();
    Notas notas = new Notas();
    Promedios pro =new Promedios();

    public InicioDocente() {

        initComponents();
           
        
        
       this.setLocationRelativeTo(null);
        

        agregarEstudiante = new AgregarEstudiante();

        eliminarEstudiante = new EliminarEstudiante();

        add(agregarEstudiante);

        add(eliminarEstudiante);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        B_notas = new javax.swing.JMenu();
        adicionar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        buscar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        listadoNotas = new javax.swing.JMenuItem();
        promedios = new javax.swing.JMenuItem();
        B_asistencia = new javax.swing.JMenu();
        listado = new javax.swing.JMenuItem();
        Listado = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setText("CERRAR SESIÓN");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        B_notas.setBackground(new java.awt.Color(153, 153, 153));
        B_notas.setBorder(null);
        B_notas.setText("NOTAS");

        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });
        B_notas.add(adicionar);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        B_notas.add(modificar);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        B_notas.add(buscar);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        B_notas.add(eliminar);

        listadoNotas.setText("Listado de notas");
        listadoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoNotasActionPerformed(evt);
            }
        });
        B_notas.add(listadoNotas);

        promedios.setText("Promedios");
        promedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promediosActionPerformed(evt);
            }
        });
        B_notas.add(promedios);

        jMenuBar1.add(B_notas);

        B_asistencia.setBackground(new java.awt.Color(153, 153, 153));
        B_asistencia.setBorder(null);
        B_asistencia.setText("ASISTENCIA");
        B_asistencia.setDelay(300);

        listado.setText("Registrar Asistencia");
        listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoActionPerformed(evt);
            }
        });
        B_asistencia.add(listado);

        Listado.setText("Listado");
        Listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoActionPerformed(evt);
            }
        });
        B_asistencia.add(Listado);

        jMenuBar1.add(B_asistencia);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(494, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoActionPerformed
        lisAsis.setX(nombre1);

        lisAsis.setVisible(true);
        eliminarEstudiante.setVisible(false);
        agregarEstudiante.setVisible(false);

//        modificarn.setVisible(false);

    }//GEN-LAST:event_listadoActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        buscarNotas.setX(nombre1);
        buscarNotas.setVisible(true);


    }//GEN-LAST:event_buscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed

        eliminarNotas.setX(nombre1);
        eliminarNotas.setVisible(true);


    }//GEN-LAST:event_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Inicio i = new Inicio();
        i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed

        adi.setX(nombre1);
        adi.setVisible(true);


    }//GEN-LAST:event_adicionarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

        modi.setX(nombre1);
        modi.setVisible(true);


    }//GEN-LAST:event_modificarActionPerformed

    private void listadoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoNotasActionPerformed

        lis.setX(nombre1);
        lis.setVisible(true);


    }//GEN-LAST:event_listadoNotasActionPerformed

    private void ListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoActionPerformed
        asis.setX(nombre1);
        asis.setVisible(true);
    }//GEN-LAST:event_ListadoActionPerformed

    private void promediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promediosActionPerformed

        pro.setX(nombre1);
        pro.setVisible(true);


    }//GEN-LAST:event_promediosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu B_asistencia;
    private javax.swing.JMenu B_notas;
    private javax.swing.JMenuItem Listado;
    private javax.swing.JMenuItem adicionar;
    private javax.swing.JMenuItem buscar;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem listado;
    private javax.swing.JMenuItem listadoNotas;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JMenuItem promedios;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen= new ImageIcon(getClass().getResource("/imagenes/logo.jpg")).getImage();
        g.drawImage(imagen,0, 0, getWidth(),getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
    
}}
