/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_docenteestudiantes;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class InicioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InicioAdmin
     */
    String nombre1;

    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }

    public String getNombre1() {
        return nombre1;
    }
    
    EliminarDocente eliminarD;
    AgregarEstudiante agregarEstudiante;

    EliminarEstudiante eliminarEstudiante;

   
    

    public InicioAdmin() {

        initComponents();
         ;
         this.setLocationRelativeTo(null);
       
        
       eliminarD= new  EliminarDocente();
        agregarEstudiante = new AgregarEstudiante();

        eliminarEstudiante = new EliminarEstudiante();
        
     

        add(agregarEstudiante);

        add(eliminarEstudiante);
        add(eliminarD);
      
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        B_estudiante = new javax.swing.JMenu();
        agregarE = new javax.swing.JMenuItem();
        eliminarE = new javax.swing.JMenuItem();
        docente = new javax.swing.JMenu();
        agregarDocente = new javax.swing.JMenuItem();
        eliminarDocente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setText("CERRAR SESIÓN");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        B_estudiante.setBackground(new java.awt.Color(153, 153, 153));
        B_estudiante.setText("ESTUDIANTES");

        agregarE.setText("Agregar");
        agregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEActionPerformed(evt);
            }
        });
        B_estudiante.add(agregarE);

        eliminarE.setText("Eliminar");
        eliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEActionPerformed(evt);
            }
        });
        B_estudiante.add(eliminarE);

        jMenuBar1.add(B_estudiante);

        docente.setBackground(new java.awt.Color(153, 153, 153));
        docente.setText("DOCENTES");

        agregarDocente.setText("Agregar");
        agregarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDocenteActionPerformed(evt);
            }
        });
        docente.add(agregarDocente);

        eliminarDocente.setText("Eliminar");
        eliminarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDocenteActionPerformed(evt);
            }
        });
        docente.add(eliminarDocente);

        jMenuBar1.add(docente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(527, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEActionPerformed

        agregarEstudiante.setVisible(true);

        eliminarEstudiante.setVisible(false);

     

    }//GEN-LAST:event_agregarEActionPerformed

    private void eliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEActionPerformed
        eliminarEstudiante.setVisible(true);

        agregarEstudiante.setVisible(false);

    }//GEN-LAST:event_eliminarEActionPerformed

    private void agregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDocenteActionPerformed
       this.setVisible(false);
        RDocente registro;
        registro = new RDocente();
        registro.setVisible(true);
    }//GEN-LAST:event_agregarDocenteActionPerformed

    private void eliminarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDocenteActionPerformed
        eliminarD.setVisible(true);
    }//GEN-LAST:event_eliminarDocenteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Inicio i = new Inicio();
        i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu B_estudiante;
    private javax.swing.JMenuItem agregarDocente;
    private javax.swing.JMenuItem agregarE;
    private javax.swing.JMenu docente;
    private javax.swing.JMenuItem eliminarDocente;
    private javax.swing.JMenuItem eliminarE;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen= new ImageIcon(getClass().getResource("/imagenes/logo.jpg")).getImage();
        g.drawImage(imagen,0, 0, getWidth(),getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
    
}}
